become_override: false
silent: false
ACTION: create

user_count: 1
user_prefix: user
namespace_prefix: globex


# ------------------------------------------------
# AMQ Streams Operator
# ------------------------------------------------

amq_streams_operator_channel: ""
amq_streams_operator_automatic_install_plan_approval: true
amq_streams_operator_starting_csv: ""
amq_streams_operator_name: amq-streams
amq_streams_operator_namespace: openshift-operators
amq_streams_operator_catalog: redhat-operators
amq_streams_operator_csv_prefix: amqstreams
amq_streams_operator_wait_for_deploy: true
amq_streams_operator_use_catalog_snapshot: false
amq_streams_operator_catalogsource_name: ""
amq_streams_operator_catalog_snapshot_image: ""
amq_streams_operator_catalog_snapshot_image_tag: ""

# ------------------------------------------------
# Red Hat SSO Operator
# ------------------------------------------------

rhsso_operator_namespace: rhsso
rhsso_operator_channel: ""
rhsso_operator_automatic_install_plan_approval: true
rhsso_operator_starting_csv: ""
rhsso_operator_name: rhsso-operator
rhsso_operator_catalog: redhat-operators
rhsso_operator_csv_prefix: rhsso-operator
rhsso_operator_wait_for_deploy: true
rhsso_operator_use_catalog_snapshot: false
rhsso_operator_catalogsource_name: ""
rhsso_operator_catalog_snapshot_image: ""
rhsso_operator_catalog_snapshot_image_tag: ""

# ------------------------------------------------
# OpenShift Gitops
# ------------------------------------------------

openshift_gitops_channel: latest
openshift_gitops_automatic_install_plan_approval: true
openshift_gitops_starting_csv: ""
openshift_gitops_pipelines_csv_prefix: openshift-pipelines-operator-rh

openshift_gitops_setup_cluster_admin: true

openshift_gitops_update_route_tls: true

openshift_gitops_update_resources: true

# ApplicationSet Controller
openshift_gitops_applicationset_controller_update: false
openshift_gitops_applicationset_controller_requests_cpu: 250m
openshift_gitops_applicationset_controller_requests_memory: 512Mi
openshift_gitops_applicationset_controller_limits_cpu: "2"
openshift_gitops_applicationset_controller_limits_memory: 1Gi

# Application Controller
openshift_gitops_controller_update: true
openshift_gitops_controller_requests_cpu: 500m
openshift_gitops_controller_requests_memory: 1Gi
openshift_gitops_controller_limits_cpu: "4"
openshift_gitops_controller_limits_memory: 4Gi
# Setting a default value for reconcile timeout as it needs to be configurable
# Reduce this value if you want to sync more frequently
openshift_gitops_controller_app_sync: 3m

openshift_gitops_controller_remove_memory_limits: false

# Redis
openshift_gitops_redis_update: false
openshift_gitops_redis_requests_cpu: 250m
openshift_gitops_redis_requests_memory: 128Mi
openshift_gitops_redis_limits_cpu: 500m
openshift_gitops_redis_limits_memory: 256Mi

# Repo Server
openshift_gitops_repo_update: true
openshift_gitops_repo_requests_cpu: 500m
openshift_gitops_repo_requests_memory: 512Mi
openshift_gitops_repo_limits_cpu: "2"
openshift_gitops_repo_limits_memory: 2Gi

# DEX
openshift_gitops_dex_update: false
openshift_gitops_dex_requests_cpu: 125m
openshift_gitops_dex_requests_memory: 128Mi
openshift_gitops_dex_limits_cpu: 500m
openshift_gitops_dex_limits_memory: 256Mi

# Server
openshift_gitops_server_update: false
openshift_gitops_server_requests_cpu: 250m
openshift_gitops_server_requests_memory: 128Mi
openshift_gitops_server_limits_cpu: 500m
openshift_gitops_server_limits_memory: 256Mi

openshift_gitops_resource_customizations: |
  operators.coreos.com/Subscription:
    health.lua: |
      health_status = {}
      if obj.status ~= nil then
        if obj.status.conditions ~= nil then
          numDegraded = 0
          numPending = 0
          msg = ""
          for i, condition in pairs(obj.status.conditions) do
            msg = msg .. i .. ": " .. condition.type .. " | " .. condition.status .. "\n"
            if condition.type == "InstallPlanPending" and condition.status == "True" then
              numPending = numPending + 1
            elseif (condition.type == "InstallPlanMissing" and condition.reason ~= "ReferencedInstallPlanNotFound") then
              numDegraded = numDegraded + 1
            elseif (condition.type == "CatalogSourcesUnhealthy" or condition.type == "InstallPlanFailed") and condition.status == "True" then
              numDegraded = numDegraded + 1
            end
          end
          if numDegraded == 0 and numPending == 0 then
            health_status.status = "Healthy"
            health_status.message = msg
            return health_status
          elseif numPending > 0 and numDegraded == 0 then
            health_status.status = "Progressing"
            health_status.message = "An install plan for a subscription is pending installation"
            return health_status
          else
            health_status.status = "Degraded"
            health_status.message = msg
            return health_status
          end
        end
      end
      health_status.status = "Progressing"
      health_status.message = "An install plan for a subscription is pending installation"
      return health_status

# ------------------------------------------------
# OpenShift Pipelines Operator
# ------------------------------------------------

openshift_pipelines_operator_name: openshift-pipelines-operator-rh
openshift_pipelines_operator_namespace: openshift-operators
openshift_pipelines_operator_channel: ""
openshift_pipelines_operator_automatic_install_plan_approval: true
openshift_pipelines_operator_starting_csv: ""
openshift_pipelines_operator_catalog: redhat-operators
openshift_pipelines_operator_csv_prefix: openshift-pipelines-operator-rh
openshift_pipelines_operator_wait_for_deploy: true
openshift_pipelines_operator_use_catalog_snapshot: false
openshift_pipelines_operator_catalogsource_name: ""
openshift_pipelines_operator_catalog_snapshot_image: ""
openshift_pipelines_operator_catalog_snapshot_image_tag: ""

# ------------------------------------------------
# Threescale Operator
# ------------------------------------------------

threescale_operator_name: 3scale-operator
threescale_operator_namespace: openshift-operators
threescale_operator_channel: "threescale-2.13"
threescale_operator_automatic_install_plan_approval: true
threescale_operator_starting_csv: ""
threescale_operator_catalog: redhat-operators
threescale_operator_csv_prefix: 3scale-operator
threescale_operator_wait_for_deploy: true
threescale_operator_use_catalog_snapshot: false
threescale_operator_catalogsource_name: redhat-operators-snapshot-amq-streams
threescale_operator_catalog_snapshot_image: ""
threescale_operator_catalog_snapshot_image_tag: ""
threescale_operator_requests_memory: 1024Mi
threescale_operator_limits_memory: 1024Mi

# ------------------------------------------------
# Apicurio Designer Operator
# ------------------------------------------------

apicurio_operator_channel: "fuse-apicurito-7.11.x"
apicurio_operator_automatic_install_plan_approval: true
apicurio_operator_starting_csv: ""
apicurio_operator_name: fuse-apicurito
apicurio_operator_namespace: apicurio-designer
apicurio_operator_catalog: redhat-operators
apicurio_operator_csv_prefix: fuse-apicurito
apicurio_operator_wait_for_deploy: true
apicurio_operator_deployment: fuse-apicurito
apicurio_operator_use_catalog_snapshot: false
apicurio_operator_catalogsource_name: ""
apicurio_operator_catalog_snapshot_image: ""
apicurio_operator_catalog_snapshot_image_tag: ""

# ------------------------------------------------
# Service Registry Operator
# ------------------------------------------------

service_registry_channel: "2.x"
service_registry_automatic_install_plan_approval: true
service_registry_starting_csv: ""
service_registry_operator_name: service-registry-operator
service_registry_operator_namespace: openshift-operators
service_registry_operator_catalog: redhat-operators
service_registry_csv_prefix: service-registry-operator
service_registry_wait_for_deploy: true
service_registry_use_catalog_snapshot: false
service_registry_catalogsource_name: ""
service_registry_catalog_snapshot_image: ""
service_registry_catalog_snapshot_image_tag: ""

# ------------------------------------------------
# Red Hat SSO
# ------------------------------------------------

rhsso_application_namespace: openshift-gitops
rhsso_application_name: rhsso
rhsso_namespace: "{{ rhsso_operator_namespace }}"
rhsso_gitops_repo: https://github.com/btison/globex-api-versioning-helm.git
rhsso_gitops_repo_tag: main
rhsso_gitops_repo_path: globex-api-versioning/globex-rhsso

rhsso_cr_name: rhsso
rhsso_external_access: false
rhsso_host: sso
rhsso_max_time_to_wait: 600000
rhsso_realm: globex
rhsso_web_gateway_client: globex-web-gateway

# ------------------------------------------------
# Globex
# ------------------------------------------------

globex_namespace: globex
globex_mw_namespace: globex-mw

globex_application_name: globex
globex_application_namespace: openshift-gitops

globex_application_repo: https://github.com/btison/globex-api-versioning-helm.git
globex_application_repo_tag: main
globex_application_repo_path: globex-api-versioning/globex

kafka_broker_name: kafka
kafka_security_protocol: SASL_PLAINTEXT
kafka_sasl_mechanism: SCRAM-SHA-512
kafka_client_id: globex
kafka_client_secret: globex

globex_user_password: openshift

# ------------------------------------------------
# Threescale
# ------------------------------------------------

threescale_application_namespace: openshift-gitops

threescale_gitops_repo: https://github.com/btison/globex-api-versioning-helm.git
threescale_gitops_repo_tag: main
threescale_gitops_repo_path: globex-api-versioning/globex-threescale

threescale_namespace: 3scale

threescale_apimanager_application_name: threescale

threescale_minio_stateful: true
threescale_minio_storageclass: ocs-external-storagecluster-ceph-rbd
threescale_minio_default_region: us-east-1
threescale_minio_access_key_id: minio
threescale_minio_secret_access_key: minio123

threescale_master_domain: 3scale-master

threescale_tenant_org_name_base: 3scale
threescale_tenant_admin_password: "openshift"

# ------------------------------------------------
# Globex APIM
# ------------------------------------------------

globex_apim_user: "{{ user_prefix }}{{ user_count }}"
globex_apim_namespace: "globex-apim-{{ globex_apim_user }}"

globex_apim_application_name: globex-apim
globex_apim_application_namespace: openshift-gitops

globex_apim_repo: https://github.com/btison/globex-api-versioning-helm.git
globex_apim_repo_tag: main
globex_apim_repo_path: globex-api-versioning/globex-apim
