---

- name: "Ensure apicurio namespace exists"
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: "{{ apicurio_namespace }}"

- name: Deploy apicurio application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'apicurio-designer-application.yaml.j2') }}"
