---

- name: Install Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: "{{ openshift_pipelines_operator_name }}"
    install_operator_namespace: "{{ openshift_pipelines_operator_namespace }}"
    install_operator_channel: "{{ openshift_pipelines_operator_channel }}"
    install_operator_csv_nameprefix: "{{ openshift_pipelines_operator_csv_prefix }}"
    install_operator_catalog: "{{ openshift_pipelines_operator_catalog }}"
    install_operator_automatic_install_plan_approval:
      "{{ openshift_pipelines_operator_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ openshift_pipelines_operator_starting_csv }}"
    install_operator_catalogsource_setup:
      "{{ openshift_pipelines_operator_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name: "{{ openshift_pipelines_operator_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: openshift-operators
    install_operator_catalogsource_image: "{{ openshift_pipelines_operator_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag:
      "{{ openshift_pipelines_operator_catalog_snapshot_image_tag | default('') }}"
